### ISSUE TITLE
doesn't work inside row and column

### ISSUE THREAD

**Issue by mrsuman3** [ralphnoel13/flutter_boom_menu#10]
gives 'A RenderFlex overflowed by Infinity pixels on the bottom.' error when used inside column widget and gives 'A RenderFlex overflowed by Infinity pixels on the right.' error when used inside row widget.

**Comment by Mohanraj153** [comment]
Hi, that's plugin uses for "floatingActionButton" menu widget only. it's not support for either column or row widget.
