### ISSUE TITLE
strange shape when use FloatingActionButtonLocation.centerDocked

### ISSUE THREAD

**Issue by kateile** [ralphnoel13/flutter_boom_menu#13]
![Nux-20200401-141141](https://user-images.githubusercontent.com/22394924/78130994-fbc62b80-7422-11ea-92a7-dc3b03502338.jpg)

**Comment by saahithyan** [comment]
As per document, you can't set FloatingActionButtonLocation.

> It's not possible to set its position with the Scaffold.floatingActionButtonLocation argument, but it's possible to set right/bottom margin with the marginRight and marginBottom arguments (default to 16) to place the button anywhere in the screen. Using the Scaffold.bottomNavigationBar the floating button will be always placed above the bar, so the BottomAppBar.hasNotch should be always false.

There is a work around though, set `marginRight` and `marginBottom` to `BoomMenu`.
Like this
```
BoomMenu(
  marginRight: MediaQuery.of(context).size.width/2 - 32 - 16,
  marginBottom: -50,
  ...
)
```

- 32 is default padding
- 16 half of my FAB icon

![Screenshot_1586161002](https://user-images.githubusercontent.com/10608534/78537956-e465b480-780d-11ea-9c19-b887b7d2efba.png)
