### ISSUE TITLE
BoomMenu requires AnimatedIcon, but there are only 14 (7x2) to chose from, Flutter not interested in adding more.

### ISSUE THREAD

**Issue by joeyda3rd** [ralphnoel13/flutter_boom_menu#20]
Like the title says, the animated icon data class doesn't have enough icons for all cases. Flutter team isn't interested in adding more and creating new ones with their in-house tool is difficult. Is there another solution to being able to use static icons that transition or something?

https://github.com/flutter/flutter/issues/42461

**Comment by celikomer** [comment]
I don't think AnimatedIcon is required. You can pass your own `child` widget to a button. If you check the class implementation, it states that `child` object will be used if `AnimatedIcon` is null. 

`  /// The child of the main button, ignored if [animatedIcon] is non [null].`
 ` final Widget child;`
