### ISSUE TITLE
Very good but with z-order problem

### ISSUE THREAD

**Issue by carmas123** [ralphnoel13/flutter_boom_menu#5]
Hi I try to use this lib but with a problem.
When I try to place this widget into my app and the menu is closed the overlay stay always on top. If I use it with a listview when the menu is closed and I try to scroll the listview the gesture is detected by menu and not by listview, this makes it unusable :(

**Comment by RalphNoel** [comment]
Hi, would you send me your error code for our better support to you.

**Comment by carmas123** [comment]
Hi, I cannot make an example because the problem became into my app and I cannot send you my app.
I try to explain you the problem.
Into a simple scaffold with a ListView when I add you lib and try to open and close the menu, after that the scrolling is not over the listview but always on the menu though if it not visible.

**Comment by Mohanraj153** [comment]
Hi, we fixed your request. Now it's on live & see the below link:
https://pub.dev/packages/flutter_boom_menu#-changelog-tab-

Thank you!

**Comment by carmas123** [comment]
Very good now work very well
