### ISSUE TITLE
Makes the body of scaffold unscrollable

### ISSUE THREAD

**Issue by mrsuman3** [ralphnoel13/flutter_boom_menu#6]
used BoomMenu widget as floatingactionbutton of Scaffold. Scaffold has body of SingleChildScrollView. Now, i can't scroll down the page.

**Comment by Mohanraj153** [comment]
Hey! we fixed your request. Now it's on live & see the below link:
https://pub.dev/packages/flutter_boom_menu#-changelog-tab-

Thank you!
